version: '3.9'
services:
  db:
    image: postgres:17
    container_name: appointment_db
    environment:
      POSTGRES_DB: appointmentapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: appointment_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appointmentapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    depends_on:
      - db

volumes:
  pgdata:
